project_id = "rfpojorabznodwaxwwvl"

[functions.generate-customer]
verify_jwt = false

[functions.generate-actions]
verify_jwt = false

[functions.generate-insights]
verify_jwt = false

[functions.ai-action-assistant]
verify_jwt = false

[functions.run-query]
verify_jwt = false
