project_id = "rfpojorabznodwaxwwvl"

[functions.generate-customer]
verify_jwt = false

[functions.generate-actions]
verify_jwt = false

[functions.generate-insights]
verify_jwt = false

[functions.ai-action-assistant]
verify_jwt = false

[functions.generate-action-insights]
verify_jwt = false

[functions.test-ai-connection]
verify_jwt = false

[functions.generate-primary-bank-data]
verify_jwt = false

[functions.run-query]
verify_jwt = false

[functions.generate-demo-audio]
verify_jwt = false

[functions.upload-file]
verify_jwt = false

[functions.test-prompt]
verify_jwt = false

[functions.test-elevenlabs-voice]
verify_jwt = false

[functions.seed-demo-users]
verify_jwt = false

[functions.rag-assistant]
verify_jwt = false